# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff-check
        args: [ --fix ]
        types_or: [ python, pyi ]
      - id: ruff-format
        types_or: [ python, pyi ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        types: [python]
      - id: fix-byte-order-marker
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: 'setup.cfg|tests/assets/reports/.*\.txt'
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: local
    hooks:
      - id: uv-lock-check
        name: uv lock is up to date
        entry: uv lock --check
        language: system
        pass_filenames: false
        files: ^(pyproject\.toml|uv\.lock)$

  # - repo: https://github.com/thlorenz/doctoc
  #   rev: v2.2.0
  #   hooks:
  #     - id: doctoc
  #       args: [ --github, --update-only ]
