# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
[project]
name = "aitune"
readme = "docs/pypi.rst"
description = "NVIDIA AITune"
dynamic = ["version"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Software Development",
    "Topic :: Scientific/Engineering",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
]
authors = [{ name = "NVIDIA Corporation" }]
maintainers = [{ name = "NVIDIA Corporation" }]
keywords = [
    "dynamo",
    "inference",
    "tune",
    "nvidia",
    "tensorrt",
    "torch-tensorrt",
    "onnx",
    "pytorch",
    "torch",
]
license = { text = "Apache 2.0" }
requires-python = ">=3.10,<3.13"
dependencies = [
    "autowrapt>=1.0",
    "dill>=0.3.8",
    "nvidia-ml-py",
    "nvidia-modelopt[onnx]>=0.40.0",
    "numpy>=2.0.0",
    "pandas>=2.3",
    "nvtx",
    "onnxscript<=0.6.1",
    "onnx-ir<=0.1.16",
    "psutil",
    "tabulate>=0.9.0",
    "tensorrt>=10.5",
    "torch>=2.7,<2.11",
    "torchao>=0.13,<0.17",
    "torch-tensorrt>2,<2.11",
    "wrapt~=2.0"
]

[project.urls]
"Documentation" = "https://ai-dynamo.github.io/aitune"
"Repository" = "https://github.com/ai-dynamo/aitune.git"
"Tracker" = "https://github.com/ai-dynamo/aitune/issues"

[dependency-groups]
test = [
    "pytest>=9.0.0",
    "pytest-mock",
    "pytest-cov",
    "pytest-xdist",
    "pillow",
    "datasets>=3.3.2",
    "transformers>=4.54,<5",
    "setuptools",
    "importlib-metadata; python_version < '3.10'",
]
dev = [
    "build >= 0.8",
    "ipython >= 7.16",
    "pdbpp >= 0.10",
    "pip >= 21.1",
    "ruff >= 0.3.0",
    "ipykernel",
    "pre-commit",
    "pre-commit-uv",
    "pytype",
    "tox",
    "uv>=0.9.0",
]
functional-test = [
    "fire",
    "timm",
    "diffusers<=0.34.0",
    "datasets>=3.3.2",
    "transformers>=4.54,<5",
    "sentencepiece>=0.2.0",
    "urllib3>=2.6.3", # sec
]
doc = [
    "PyYAML >= 6.0",
]
dynamo = [
    "ai-dynamo-runtime>=0.1",
    "uvloop",
]
torch210 = [
    "torch==2.10",
    "torch-tensorrt>=2.10",
    "torchao>=0.16",
    "nvidia-cuda-runtime-cu13==0.0.0a0"
]



[build-system]
requires = ["setuptools>=65.3.0", "setuptools_scm[toml]>=8.3", "wheel>=0.37.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true
license-files = ["LICENSE"]

[tool.setuptools.packages.find]
namespaces = false
include = ["aitune"]

[tool.setuptools.package-data]
aitune = ["**/*"]

[tool.setuptools_scm]

[tool.uv]
managed = true

[tool.pytest.ini_options]
log_cli = true
addopts = ["--import-mode=importlib", "--doctest-modules"]
pythonpath = ["."]
testpaths = ["aitune", "tests/unit"]
markers = [
    "slow: mark test as slow",
    "dynamo: mark test as requiring ai-dynamo-runtime (skip without aitune[dynamo])",
]

[tool.ruff]
preview = true
line-length = 120
indent-width = 4
target-version = "py310"

[tool.ruff.lint]
select = [
    "A",
    "B",
    "C",
    "C4",
    "C90",
    "D",
    "E",
    "F",
    "I",
    "N",
    "W",
    "T",
    "T10",
    "T20",
    "UP",
    "CPY",
    "G004"
]
ignore = ["E266", "E501", "N818"]
exclude = ["**/*.ipynb"]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["D104"]
"**/__version__.py" = ["D100"]
"**/{tests,docs,tools,examples}/*" = ["C416", "D", "T201"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.flake8-copyright]
notice-rgx = "# SPDX-FileCopyrightText: Copyright \\(c\\) 2026 NVIDIA CORPORATION & AFFILIATES\\. All rights reserved\\.(\n# SPDX-FileCopyrightText: .*)*\n# SPDX-License-Identifier: Apache-2\\.0"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

[tool.vulture]
exclude = []
ignore_decorators = []
ignore_names = []
make_whitelist = true
min_confidence = 80
paths = ["aitune"]
sort_by_size = true
verbose = false

[tool.pytype]
disable = ["import-error", "module-attr"]

# the following enables autowrapt to conditionally enable JIT tuning i.e. `AUTOWRAPT_BOOTSTRAP=aitune_enable_jit_tuning python script.py`
[project.entry-points.aitune_enable_jit_tuning]
torch = "aitune.torch.jit.enable:wrapt_auto_enable"
