# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
[tox]
envlist = py310, py311, py312, pytype, pre-commit, pytorch
isolated_build = True

[testenv]
setenv =
    PYTEST_ADDOPTS=--import-mode append --junitxml={env_name}.test-report.xml -vv --basetemp={envtmpdir} -o junit_suite_name={env_name}
    PIP_EXTRA_INDEX_URL=https://pypi.nvidia.com
passenv =
    HF_HOME
    HF_TOKEN
    HF_ENDPOINT
commands =
    pytest
extras =
    test
runner = virtualenv

[testenv:pytype]
basepython = python3
commands =
    pytype --keep-going -j auto aitune tests examples
deps = pytype

[testenv:pre-commit]
basepython = python3
commands =
    pre-commit run -a
deps =
    pre-commit
    pre-commit-uv

[testenv:pytorch]
basepython = python3
sitepackages = true
extras =
    test
allowlist_externals =
    pytest
commands =
    pytest tests/unit

[testenv:windows]
setenv =
    {[testenv]setenv}
    USERNAME=user
commands =
    pytest tests/unit
extras =
    test