# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[project]
name = "aitune-examples-common"
version = "0.1.0"
description = "NVIDIA AITune Examples Common"
requires-python = ">=3.10, <3.13"

[build-system]
requires = ["setuptools>=65.3.0", "wheel>=0.37.1"]
build-backend = "setuptools.build_meta"

[tool.aitune]
skip = true
