# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[project]
name = "ai-tune-esm2-example"
version = "0.1.0"
description = "NVIDIA AITune ESM2 Example"
readme = "README.md"
license = { text = "Apache 2.0" }
requires-python = ">=3.10, <3.13"

dependencies = [
    "aitune",
    "aitune-examples-common",
    "transformers<5",
    "sentencepiece",
    "protobuf",
    "colored",
]

[project.optional-dependencies]
dynamo = [
    "aitune-examples-common",
    "ai-dynamo>=1.3,<2.0.0",
    "fastapi",
    "uvicorn",
    "aiohttp",
    "aiofiles",
    "uvloop",
    "pyyaml",
]

[tool.uv.sources]
aitune = { path = "../../" }
aitune-examples-common = { path = "../../examples/common" }

[project.scripts]
tune = "esm2.tune:tune"
inference = "esm2.infer:infer"

[build-system]
requires = ["setuptools>=65.3.0", "wheel>=0.37.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
namespaces = false
include = ["esm2"]

[tool.setuptools.package-data]
esm2 = ["**/*"]

[tool.aitune]
additional_tags = ["gpu/a100"]
use_gated_hf_token = true
