# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[project]
name = "ai-tune-diffusion-jit-tuning-example"
version = "0.1.0"
description = "NVIDIA AITune Diffusion JIT Tuning Example"
readme = "README.md"
license = { text = "Apache 2.0" }
requires-python = ">=3.10, < 3.13"

dependencies = [
    "aitune",
    "diffusers>=0.25.0,<0.35",
    "transformers<5",
    "pillow",
    "sentencepiece",
    "protobuf",
    "timm",
]

[tool.uv.sources]
aitune = { path = "../../" }

[project.scripts]
resnet = "jit_tuning.resnet:main"
diffusion = "jit_tuning.diffusion:main"

[build-system]
requires = ["setuptools>=65.3.0", "wheel>=0.37.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
namespaces = false
include = ["jit_tuning"]

[tool.setuptools.package-data]
jit_tuning = ["**/*"]

[tool.aitune]
skip = true
