# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
FROM python:3.12-slim

WORKDIR /opt/aitune

COPY dist/*.whl /tmp/

RUN test "$(find /tmp -maxdepth 1 -name "*.whl" | wc -l)" -eq 1 && python -m pip install --no-cache-dir --no-deps /tmp/*.whl && python -c "import aitune"
