# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

Backend:
  model_name: intfloat/e5-large-v2
  max_batch_size: 8
  batch_timeout: 0.5
  force_tune: false
  tuned_model_path: e5large_tuned.pt

