# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[project]
name = "nvidia-ai-tune-e5-large-v2-embedding-example"
version = "0.1.0"
description = "NVIDIA AI Tune E5 Large V2 Embedding Example"
readme = "README.md"
license-files = ["LICENSE"]
requires-python = ">=3.10, <3.13"

dependencies = [
    "aitune",
    "aitune-examples-common",
    "sentence_transformers",
    "huggingface_hub",
]

[project.optional-dependencies]
dynamo = [
    "aitune-examples-common",
    "ai-dynamo<2.0.0",
    "uvicorn",
    "aiohttp",
    "aiofiles>=24.1.0",
    "python-multipart",
    "pyyaml",
]

[tool.uv.sources]
aitune = { path  = "../../", editable = true }
aitune-examples-common = { path = "../../examples/common" }

[project.scripts]
tune = "e5large.tune:main"
inference = "e5large.inference:main"

[build-system]
requires = ["setuptools>=65.3.0,<82", "setuptools_scm>=2.0.0,<3", "wheel>=0.37.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
namespaces = false
include = ["e5large"]

[tool.setuptools.package-data]
e5large = ["e5large/*"]

[tool.ruff]
preview = true
line-length = 120
indent-width = 4
target-version = "py310"

[tool.ruff.lint]
select = ["B", "C", "C4", "C90", "D", "E", "F", "I", "N", "W", "T", "T10", "T20", "UP", "CPY"]
ignore = ["E266", "E501", "N818"]
exclude = []

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["D104"]
"**/__version__.py" = ["D100"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.aitune]
docker_image = "nvcr.io/nvidia/pytorch:25.10-py3"
dependencies = ["torchao~=0.15.0"]
