# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
Backend:
  model_name: "resnet50"
  max_batch_size: 4
  batch_timeout: 0.5
  image_path: "/opt/aitune/dynamo/app/dog.webp"
  classes_file: "/opt/aitune/dynamo/app/imagenet_classes.txt"
  image_storage_path: "/images"
  pretrained: true
  force_tune: false
  tuned_model_path: null

Frontend:
  port: 8000
