# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
Backend:
  model_name: "stabilityai/stable-diffusion-3-medium-diffusers"
  max_batch_size: 4
  batch_timeout: 2.0
  pretrained: true
  prompt: "A beautiful sunset over a calm ocean"
  sizes: [[512, 512]]
  steps: 10
  tuned_model_path: "stable_diffusion.ait"
  force_tune: false
  image_storage_path: "/images"
  ServiceArgs:
    workers: 1
    resources:
      cpu: "8"
