# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[project]
name = "ai-tune-stable-diffusion-example"
version = "0.1.0"
description = "NVIDIA AITune Stable Diffusion 3 Example"
readme = "README.md"
license = { text = "Apache 2.0" }
requires-python = ">=3.10, <3.13"

dependencies = [
    "aitune",
    "diffusers>=0.25.0,<0.35",
    "torch>=2.0.0",
    "transformers<5",
    "pillow",
    "sentencepiece",
    "protobuf",
]

[project.optional-dependencies]
dynamo = [
    "aitune-examples-common",
    "ai-dynamo==0.6.0",
    "uvicorn",
    "aiohttp",
    "aiofiles",
    "uvloop",
    "pyyaml",
]

[tool.uv.sources]
aitune = { path = "../../" }
aitune-examples-common = { path = "../../examples/common" }

[project.scripts]
tune = "stable_diffusion.tune:main"
inference = "stable_diffusion.inference:main"

[build-system]
requires = ["setuptools>=65.3.0", "wheel>=0.37.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
namespaces = false
include = ["stable_diffusion"]

[tool.setuptools.package-data]
stable_diffusion = ["**/*"]

[tool.aitune]
additional_tags = ["mem/80g"]
use_gated_hf_token = true
